check:
  - overlays-build
overlays_dir: overlays
overlays:
  - name: ps-nlp
    build:
      base-image: "quay.io/thoth-station/s2i-generic-data-science-notebook:v0.2.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: thoth-station
      registry-project: ps-nlp
      registry-secret: thoth-station-thoth-pusher-secret

  - name: ps-nlp-pytorch
    build:
      base-image: "quay.io/thoth-station/s2i-generic-data-science-notebook:v0.2.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: thoth-station
      registry-project: ps-nlp-pytorch
      registry-secret: thoth-station-thoth-pusher-secret

  - name: ps-nlp-tensorflow
    build:
      base-image: "quay.io/thoth-station/s2i-generic-data-science-notebook:v0.2.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: thoth-station
      registry-project: ps-nlp-tensorflow
      registry-secret: thoth-station-thoth-pusher-secret
